apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/jujulka26/k8s-devops-pipeline-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://db:5432/appdb
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
